# keycloak helm values (ingress)

# Ingress config
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    # Enable cert-manager to create automatically the SSL certificate and store in Secret
    # Possible Cluster-Issuer values:
    #   * 'letsencrypt-issuer' (valid TLS certificate using IONOS API)
    #   * 'ca-issuer' (CA-signed certificate, not valid)
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    cert-manager.io/common-name: sso.${CLUSTER_DOMAIN}
    # Increasing proxy buffer size to avoid
    # https://stackoverflow.com/questions/57503590/upstream-sent-too-big-header-while-reading-response-header-from-upstream-in-keyc
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  rules:
    - host: sso.${CLUSTER_DOMAIN}
      # Paths for the host
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - sso.${CLUSTER_DOMAIN}
      secretName: sso-tls