---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/prometheus-operator-crds/app/overlays/prod
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: prometheus-operator-crds
      namespace: kube-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds-config
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds-app
  path: ./kubernetes/platform/prometheus-operator-crds/config/overlays/prod
  prune: true