apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - fluentd-certificate.yaml
  - fluentd-elastic-templates-cm.yaml
  - fluentd-externalsecret.yaml
  - fluentd-extservice.yaml
  - fluentd-env-cm.yaml
  - helm.yaml
  - servicemonitor.yaml

configMapGenerator:
  - name: fluentd-helm-values
    files:
      - base-values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml