---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keycloak
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: keycloak
      version: 21.7.1
      sourceRef:
        kind: HelmRepository
        name: keycloak
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  valuesFrom:
  - kind: ConfigMap
    name: keycloak-helm-values
    valuesKey: base-values.yaml