---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keycloak
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 21.7.1
      sourceRef:
        kind: HelmRepository
        name: keycloak
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  valuesFrom:
  - kind: ConfigMap
    name: keycloak-helm-values
    valuesKey: base-values.yaml