# keycloak helm values (base)
global:
  storageClass: longhorn

# Run in production mode behind NGINX proxy terminating TLS sessions
# ref: https://www.keycloak.org/server/reverseproxy
# edge proxy mode: Enables communication through HTTP between the proxy and Keycloak.
# This mode is suitable for deployments with a highly secure internal network where the reverse proxy keeps a secure connection (HTTP over TLS) with clients while communicating with Keycloak using HTTP.
production: true
proxy: edge

# TEMP WORKAROUND
# https://github.com/bitnami/charts/issues/28154
proxyHeaders: xforwarded
#

# Admin user
auth:
  existingSecret: keycloak-secret
  adminUser: admin




