---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-cluster-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: book-
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: istio-app
    - name: istio-gateway-app
  path: ./kubernetes/apps/book-info/app/overlays/prod
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings