---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  url: https://charts.external-secrets.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: external-secrets-helm-values
    valuesKey: base-values.yaml