---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/cert-manager/app/overlays/prod
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-webhook-ionos
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-app
  path: ./kubernetes/platform/cert-manager/webhook-ionos/overlays/prod
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-app
    - name: cert-manager-webhook-ionos
    - name: external-secrets-config
  path: ./kubernetes/platform/cert-manager/config/overlays/prod
  prune: true