---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cnpg-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn-app
  path: ./kubernetes/platform/cloudnative-pg/app/overlays/prod
  prune: true
