---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/external-secrets/app/overlays/prod
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-app
  path: ./kubernetes/platform/external-secrets/config/overlays/prod
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings