---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-db
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloudnative-pg-app
  path: ./kubernetes/platform/keycloak/db/overlays/prod
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keycloak-db
  path: ./kubernetes/platform/keycloak/app/overlays/prod
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: true

