---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: velero
spec:
  url: https://vmware-tanzu.github.io/helm-charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: velero
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: velero-helm-values
    valuesKey: base-values.yaml