---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mongodb-community-operator
spec:
  url: https://mongodb.github.io/helm-charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-community-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: community-operator
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: mongodb-community-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  valuesFrom:
  - kind: ConfigMap
    name: mongodb-community-operator-helm-values
    valuesKey: base-values.yaml