---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ .app_name }}
spec:
  url: {{ .chart_repo_url }}
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .app_name }}
spec:
  interval: 30m
  chart:
    spec:
      chart: {{ .chart_name }}
      version: {{ .chart_version }}
      sourceRef:
        kind: HelmRepository
        name: {{ .app_name }}
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: {{ .app_name }}-helm-values
    valuesKey: base-values.yaml