---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
spec:
  url: https://charts.min.io/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: minio
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  valuesFrom:
  - kind: ConfigMap
    name: minio-helm-values
    valuesKey: base-values.yaml