---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pi-cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: flux
  url: https://github.com/ricsanfre/pi-cluster.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: pi-cluster
