---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
spec:
  url: https://charts.jetstack.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.15.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-helm-values
    valuesKey: base-values.yaml