---
all:
  children:
    control:
      hosts:
        pimaster:
          hostname: pimaster
          ansible_host: localhost
          ansible_connection: local
    picluster:
      hosts:
        node1:
          hostname: clusterpi1
          ansible_host: 10.0.0.11
        node2:
          hostname: clusterpi2
          ansible_host: 10.0.0.12
        node3:
          hostname: clusterpi3
          ansible_host: 10.0.0.13
    raspberrypi:
      hosts:
        node[1:3]:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node[1:3]:
        k3s_worker:
          hosts:
            node[5:6]:
    dns:
      hosts:
        node1:
    pxe:
      hosts:
        node1:
    vault:
      hosts:
        node1:
    haproxy:
      hosts:
        node1:
    san:
      hosts:
        node1:
