apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: efk
  namespace: elastic
  # annotations:
  #   "helm.sh/hook": post-install,post-upgrade
spec:
  version: 8.13.0
  count: 1
  elasticsearchRef:
    name: efk
  podTemplate:
    spec:
      # Limiting Resources consumption
      containers:
      - name: kibana
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi" 
