kind: Secret
apiVersion: v1
metadata:
  name: es-prometheus-roles-secret
  namespace: elastic
stringData:
  roles.yml: |-
    prometheus_role:
      cluster: [
        'monitor',
        'monitor_snapshot'
      ] 
      indices:
      - names: [ '*' ]
        privileges: [ 'monitor', 'view_index_metadata' ]