---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coredns
spec:
  url: https://coredns.github.io/helm
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  interval: 30m
  chart:
    spec:
      chart: coredns
      version: 1.31.0
      sourceRef:
        kind: HelmRepository
        name: coredns
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: coredns-helm-values
    valuesKey: base-values.yaml